### ISSUE TITLE
A animação da linha incluída na navbar está com problemas

### ISSUE THREAD

**Issue by 1mrschneider** [1mrschneider/mermas_digitais_app#11]
### Adicionei uma "linha" para indicar qual ícone está selecionado na navbar, essa linha é na verdade um animatedContainer. Não sei se há uma forma mais simples de implementar isso.

A animação é controlada por uma variável booleana (selected), quando o estado dela é alterado o animatedContainer recebe mundaças na cor e no tamanho, isso faz com que a animação se inicie.

```
lineAnimation() {
    selected = !selected;
  }

  ativatedIcon(IconData icon) {
    return Column(
      children: [
        Icon(
          icon,
          size: 38,
          color: const Color.fromARGB(255, 221, 199, 248),
        ),
        const SizedBox(height: 6),
        AnimatedContainer(
          onEnd: () => setState(() {
            selected = true;
          }),
          curve: Curves.elasticOut,
          duration: const Duration(milliseconds: 300),
          width: selected ? 38 : 10,
          decoration: BoxDecoration(
              border: Border(
                  bottom: BorderSide(
            width: 1.0,
            color: selected
                ? const Color.fromARGB(255, 221, 199, 248)
                : Colors.transparent,
          ))),
        ),
      ],
    );
```

O BottomNavigationBarItem recebe o objeto acima em "activeIcon"

```

BottomNavigationBarItem(
                tooltip: 'Comunicados',
                icon: Icon(widgetIcons[0]),
                activeIcon: ativatedIcon(widgetIcons[0]),
                label: '',
              ),

```

E a bool "selected" é alterada quando o index muda

```
 onTap: (index) => setState(() {
              indexOf = index;
              selected = !selected;    
            }),

```

O problema é que quando eu mudo de tela, essa booleana recebe uma alternância de true para false e quando está em false a "linha" não é exibida.

[Modificação referente a esse commit](https://github.com/1mrschneider/mermas_digitais_app/commit/89f7eccb36e82668ced2b62b238f62f6f1270eb8)

**Comment by gzeloni** [comment]
Corrigido.
