### ISSUE TITLE
As funções getUserInfo e userInfo não estão funcionando

### ISSUE THREAD

**Issue by 1mrschneider** [1mrschneider/mermas_digitais_app#7]
Função userInfo:

```
Future userInfo(
    {String? userUID,
    double? userFrequence,
    required String userName,
    required String userEmail,
    required String userProfilePhoto,
    required user}) async {
  try {
    final docRef = FirebaseFirestore.instance.collection("users").doc(user.uid);
    final doc = await docRef.get();
    final data = doc.data() as Map<String, dynamic>;

    userUID = user.uid;
    userName = data['name'];
    userEmail = data['email'];
    userFrequence = data['frequence'];

    final profilephotoRef = FirebaseStorage.instance
        .ref()
        .child('users/${user.uid}/profilephoto.jpg');

    await profilephotoRef.getDownloadURL().then((value) {
      userProfilePhoto = value;
    });
  } catch (e) {
    return print('Banco de dados vazio!');
  }
}
```

Trecho aonde a função é utilizada em  \lib\src\screens\menuPages\frequencia_page.dart

```
 final user = FirebaseAuth.instance.currentUser!;

  String userUID = '';
  String userEmail = '';
  String userName = '';
  double userFrequence = 0;
  String userProfilePhoto = '';

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: userInfo(
          user: user,
          userUID: user.uid,
          userEmail: userEmail,
          userName: userName,
          userFrequence: userFrequence,
          userProfilePhoto: userProfilePhoto),
```

Dessa forma a saída no terminal é:

```
W/NetworkRequest(26441): No App Check token for request.
I/flutter (26441): Banco de dados vazio
```

Tem alguma ideia de onde está a falha na implementação? @gzeloni

**Comment by 1mrschneider** [comment]
O mesmo serve para a função getUserInfo

**Comment by gzeloni** [comment]
Essa página de frequência não está vazia?

Pois na tela de editar o usuário eu uso a mesma função, o mesmo método para instanciar o firebase e funciona.
Não é por conta do banco de dados não ter informações ou a coleção chamada estar errada?

**Comment by 1mrschneider** [comment]
Não está vazia. A coleção referenciada no código contem dados

**Comment by 1mrschneider** [comment]
Reparei nesse erro relacionado a autenticação, mas através dos prints pelo terminal consigo ver se o usuário está ou não logado, e está! Acredito que o erro está na forma como a coleção é referenciada ou em como as funções são chamadas nas telas de frequência e perfil. Da forma que eu implementei estavam funcionando, após as alterações eu não consegui ler muito bem. Fiquei um pouco perdido no código, confesso! kkkkkkkkkkkkkkkk

**Comment by gzeloni** [comment]
Mas o token ainda é válido?
Quando você fez a build, fez com um token existente, mas eles expiram com o tempo.

A classe CheckLogin busca um snapshot, não importando se é válido ou não.
Tendo um snapshot (token), ele te leva pra tela inicial.

**Comment by gzeloni** [comment]
> Reparei nesse erro relacionado a autenticação, mas através dos prints pelo terminal consigo ver se o usuário está ou não logado, e está! Acredito que o erro está na forma como a coleção é referenciada ou em como as funções são chamadas nas telas de frequência e perfil. Da forma que eu implementei estavam funcionando, após as alterações eu não consegui ler muito bem. Fiquei um pouco perdido no código, confesso! kkkkkkkkkkkkkkkk

Vou analisar certinho e te passo aqui.

Com o usuário que você me passou, consegui verificar a tela de edição do perfil e etc, mas pensei que a tela de frequência estava vazia, então não dei tanta importância.

**Comment by gzeloni** [comment]
```
 final user = FirebaseAuth.instance.currentUser!;

  String? userUID;
  String? userEmail;
  String? userName;
  double? userFrequence;
  String? userProfilePhoto;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: userInfo(
          user: user,
          userUID: user.uid,
          userEmail: userEmail,
          userName: userName,
          userFrequence: userFrequence,
          userProfilePhoto: userProfilePhoto),
```

tenta dessa forma, deixando as variáveis nullable, para que recebam os dados quando o userInfo() for executado no ```future```
